# Generated by Django 5.2.15 on 2026-06-21 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('model', models.CharField(max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model', '-timestamp'], name='audit_audit_model_0fc846_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('critical', 'Critical')], default='error', max_length=10)),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_error_timesta_ef07a5_idx'), models.Index(fields=['resolved', '-timestamp'], name='audit_error_resolve_024060_idx'), models.Index(fields=['exception_type'], name='audit_error_excepti_eb7f32_idx')],
            },
        ),
    ]
